name: Download Coverage Reports
description: Download the github artifact created with the `test --coverage`

inputs:
  sha:
    description: 'SHA to use for the artifact name'
    required: false
    default: ${{ github.sha }}

runs:
  using: composite
  steps:
    - name: Download coverage report
      uses: actions/download-artifact@v4
      with:
        name: ngx-deploy-npm-coverage-report-${{ inputs.sha }}
        path: coverage/packages/ngx-deploy-npm
