name: Migrate Nx Workspace
description: Migrate Nx Workspace to the specified version
inputs:
  nx-version:
    description: Nx version to try to migrate
    required: true

runs:
  using: composite
  steps:
    - name: Migrate
      shell: bash
      run: |
        npx nx migrate {nx-version}
        npm install --force --ignore-scripts
        npx nx migrate --run-migrations --if-exists
