/**
 * Simulates squash-merge (PR title as commit message), runs semver dry-run,
 * and writes comment.md for the PR release preview bot comment.
 */
import { execFileSync, spawnSync } from 'child_process';
import { existsSync, readFileSync, writeFileSync } from 'fs';
import { join } from 'path';

const COMMENT_MARKER = '<!-- ngx-deploy-npm-release-preview -->';
const COMMENT_FILE = process.env.COMMENT_FILE ?? 'comment.md';
const SEMVER_LOG = process.env.SEMVER_LOG ?? '/tmp/semver.log';
const PACKAGE_JSON = join('packages', 'ngx-deploy-npm', 'package.json');

const prTitle = requireEnv('PR_TITLE');
const baseRef = requireEnv('BASE_REF');
const prHeadSha = requireEnv('PR_HEAD_SHA');
const commitlintOk = process.env.COMMITLINT_OK === '1';
const commitlintOutput =
  process.env.COMMITLINT_OUTPUT ??
  (existsSync('commitlint.err') ? readFileSync('commitlint.err', 'utf-8') : '');

function requireEnv(name: string): string {
  const value = process.env[name];
  if (!value) {
    console.error(`Missing required environment variable: ${name}`);
    process.exit(1);
  }
  return value;
}

function escapeMdInline(text: string): string {
  return text.replace(/`/g, '\\`');
}

const ANSI_ESCAPE_PATTERN = new RegExp(
  `${String.fromCharCode(27)}\\[[0-9;]*m`,
  'g'
);

function stripAnsi(text: string): string {
  return text.replace(ANSI_ESCAPE_PATTERN, '');
}

function runGit(args: string[]): void {
  execFileSync('git', args, {
    stdio: 'inherit',
    env: { ...process.env, HUSKY: '0' },
  });
}

function getCurrentVersion(): string {
  try {
    const pkg = JSON.parse(readFileSync(PACKAGE_JSON, 'utf-8')) as {
      version?: string;
    };
    return pkg.version ?? 'unknown';
  } catch {
    return 'unknown';
  }
}

function simulateSquashAndDryRun(): { ok: boolean; log: string } {
  runGit(['fetch', 'origin', baseRef]);
  runGit(['checkout', '-B', 'release-preview', `origin/${baseRef}`]);
  runGit(['merge', '--squash', prHeadSha]);
  runGit(['commit', '--no-verify', '-m', prTitle]);

  const result = spawnSync(
    'npx',
    ['nx', 'run', 'ngx-deploy-npm:version', '--dry-run'],
    {
      encoding: 'utf-8',
      env: { ...process.env, HUSKY: '0' },
    }
  );

  const log = stripAnsi(`${result.stdout ?? ''}${result.stderr ?? ''}`);
  writeFileSync(SEMVER_LOG, log);

  return { ok: result.status === 0, log };
}

interface ParsedSemver {
  versionSection: string;
  changelogSection: string;
  parseFailed: boolean;
}

function parseSemverLog(logContent: string): ParsedSemver {
  if (logContent.includes('Nothing changed since last release')) {
    return {
      versionSection:
        'No npm release for this PR (no changes under `packages/ngx-deploy-npm` since the last tag).',
      changelogSection: '',
      parseFailed: false,
    };
  }

  const versionMatch = logContent.match(/Calculated new version "([^"]+)"/);
  const newVersion = versionMatch?.[1];

  if (!newVersion) {
    return {
      versionSection: '⚠️ Could not determine version from semver output.',
      changelogSection: logContent.split('\n').slice(-30).join('\n'),
      parseFailed: true,
    };
  }

  const currentVersion = getCurrentVersion();
  const changelogSection = extractChangelogBlock(logContent);

  return {
    versionSection: `\`${currentVersion}\` → \`${newVersion}\``,
    changelogSection,
    parseFailed: false,
  };
}

function extractChangelogBlock(logContent: string): string {
  const lines = logContent.split('\n');
  const parts: string[] = [];
  let delimiterCount = 0;
  let capturing = false;

  for (const line of lines) {
    if (line === '---') {
      delimiterCount++;
      if (delimiterCount === 1) {
        capturing = true;
        continue;
      }
      if (delimiterCount === 2) {
        break;
      }
    }
    if (capturing && delimiterCount === 1) {
      parts.push(line);
    }
  }

  const block = parts.join('\n').trim();
  return block || '_No changelog block in dry-run output._';
}

function buildCommentHeader(): string {
  const titleEscaped = escapeMdInline(prTitle);
  return `${COMMENT_MARKER}

## Release preview

> Simulates **squash merge** into \`${baseRef}\` using the **PR title** as the commit message.
> Only changes under \`packages/ngx-deploy-npm\` affect the version.

**PR title:** \`${titleEscaped}\`

`;
}

function buildCommitlintSection(): string {
  if (commitlintOk) {
    return `### Semantic commit (PR title)

✅ Valid conventional commit
`;
  }

  const output = commitlintOutput.trim() || '(no commitlint output)';
  return `### Semantic commit (PR title)

❌ **Invalid** — PR title must follow [Conventional Commits](https://www.conventionalcommits.org/):

\`\`\`
${output}
\`\`\`
`;
}

function buildFooter(): string {
  return `
---
*Generated by CI (PR Release Preview). Actual release runs on merge via publishment.yml.*

**Notes:** Preview uses only the PR title (squash merge). Changes outside \`packages/ngx-deploy-npm\` do not trigger a version bump. Breaking changes must appear in the title (e.g. \`feat!:\`), not only in the PR description.
`;
}

function buildVersionSection(
  versionSection: string,
  changelogSection: string
): string {
  let body = `

### Version

${versionSection}
`;

  if (changelogSection) {
    body += `
### Changelog preview

\`\`\`markdown
${changelogSection}
\`\`\`
`;
  }

  return body;
}

function writeComment(content: string): void {
  writeFileSync(COMMENT_FILE, content);
}

function main(): void {
  let comment = buildCommentHeader() + buildCommitlintSection();

  if (!commitlintOk) {
    comment += `

### Version

_Preview skipped — fix the PR title first._
`;
    writeComment(comment + buildFooter());
    process.exit(0);
  }

  try {
    const { ok, log } = simulateSquashAndDryRun();
    if (!ok) {
      comment += `

### Version

❌ **Semver dry-run failed.** See workflow logs for details.
`;
      if (log) {
        const tail = log.split('\n').slice(-40).join('\n');
        comment += `
<details>
<summary>Semver output (last 40 lines)</summary>

\`\`\`
${tail}
\`\`\`

</details>
`;
      }
      writeComment(comment + buildFooter());
      process.exit(1);
    }

    const parsed = parseSemverLog(log);
    comment += buildVersionSection(
      parsed.versionSection,
      parsed.changelogSection
    );
    writeComment(comment + buildFooter());

    if (parsed.parseFailed) {
      process.exit(1);
    }
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    comment += `

### Version

❌ **Release preview failed:** ${message}
`;
    writeComment(comment + buildFooter());
    process.exit(1);
  }
}

main();
