name: Angular E2E Test

on: workflow_call

jobs:
  angular-e2e-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup

      - uses: ./.github/actions/download-build

      - name: yarn link
        shell: bash
        run: |
          cd dist/packages/ngx-deploy-npm
          yarn link

      - name: Execute e2e test
        run: ./tools/create-angular-workspace.sh
