name: Backwards Compatibility Test

on: workflow_call

jobs:
  backwards-compatibility-test:
    strategy:
      matrix:
        nx-version: ['', '18.3.5', '17.3.2', '16.10.0'] # '' means current workspace version
    uses: ./.github/workflows/integration-test-nx-workspace.yml
    with:
      nx-version: ${{matrix.nx-version}}
