name: Backwards Compatibility Test
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # daily at 00:00

jobs:
  integration-test:
    strategy:
      matrix:
        nx-version: [latest, '16.10.0']
    uses: ./.github/workflows/integration-test.yml
    with:
      nx-version: ${{matrix.nx-version}}
