name: Essential Test

on: workflow_call

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup

      - name: Lint
        run: npx nx lint ngx-deploy-npm

      - name: Lint report
        run: npx nx lint-report ngx-deploy-npm

      - name: Archive lint report results
        uses: actions/upload-artifact@v3
        with:
          name: lint-report-${{ github.sha }}
          path: reports

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup

      - run: npx nx build ngx-deploy-npm

      - name: Archive build result
        uses: actions/upload-artifact@v3
        with:
          name: library-dist-${{ github.sha }}
          path: dist

  unit-test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup

      - run: npx nx test ngx-deploy-npm --configuration="ci"

      - if: ${{ matrix.os == 'ubuntu-latest' }}
        name: Archive coverage report
        uses: actions/upload-artifact@v3
        with:
          name: ngx-deploy-npm-coverage-report-${{ github.sha }}
          path: coverage/packages/ngx-deploy-npm/lcov.info
