name: PR's
on:
  push:
    branches-ignore:
      - 'master'
    pull_request:
      branches:
        - '**'
jobs:
  pr-test:
    uses: bikecoders/ngx-deploy-npm/.github/workflows/basic-test.yml@master #@master
