name: Incoming Versions Compatibility Test
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # daily at 00:00

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup

      - run: npx nx build ngx-deploy-npm

      - name: Archive build result
        uses: actions/upload-artifact@v4
        with:
          name: library-dist-${{ github.sha }}
          path: dist

  backwards-compatibility-test:
    needs: build
    strategy:
      matrix:
        nx-version: [latest]
    uses: ./.github/workflows/smoke-test-nx-workspace.yml
    with:
      nx-version: ${{matrix.nx-version}}
