name: Incoming Versions Compatibility Test
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # daily at 00:00

jobs:
  backwards-compatibility-test:
    strategy:
      matrix:
        nx-version: [latest]
    uses: ./.github/workflows/integration-test-nx-workspace.yml
    with:
      nx-version: ${{matrix.nx-version}}
