name: E2E Test

on:
  workflow_call:
    inputs:
      # Install @nrwl@next instead of the current one on the package.json
      install-next-version:
        type: boolean
        default: false
        required: false

jobs:
  e2e-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14, 16, 18]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup
        with:
          node-version: ${{ matrix.node-version }}

      # Perform e2e with @nrwl@next
      - if: inputs.install-next-version == true
        name: install @nrwl@next
        run: npx update-by-scope -t next @nrwl

      - run: npx nx e2e ngx-deploy-npm-e2e
