name: E2E Test

on: workflow_call

jobs:
  e2e-test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup

      - run: npx nx e2e ngx-deploy-npm-e2e --configuration="ci"
