name: Integration Test

on:
  workflow_call:
    inputs:
      nx-version:
        type: string
        description: The Nx Workspace version to run the integration test
        required: false

jobs:
  integration-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup

      - name: Read package.json Nx and set default parameter
        id: set-default-param
        run: |
          version=$(jq -r '.devDependencies.nx'package.json)
          if [ -z "${{ github.event.inputs.nx-version }}" ]; then
            echo "Setting default value for nx-version parameter: $version"
            echo "NX_VERSION=$version" >> $GITHUB_ENV
          else
            echo "Using provided value for nx-version parameter: ${{ github.event.inputs.nx-version }}"
            echo "NX_VERSION=${{ github.event.inputs.nx-version }}" >> $GITHUB_ENV
          fi

      - name: Integration Test
        run: npx nx create-nx-workspace ngx-deploy-npm -- $NX_VERSION
