name: Integration Test

on:
  workflow_call:
    inputs:
      nx-version:
        type: string
        description: The Nx Workspace version to run the integration test
        required: true

jobs:
  integration-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup

      - name: Integration Test
        run: npx nx create-nx-workspace -- ${{ inputs.nx-version }}
