name: PRs
on:
  pull_request:
    types: [opened, synchronize, reopened]

env:
  PR_NUMBER: ${{ github.event.pull_request.number }}

jobs:
  pr-test:
    uses: ./.github/workflows/basic-test.yml

  pr-e2e-test:
    uses: ./.github/workflows/e2e-test.yml

  check-commit-lint:
    name: Check commit message follows guidelines
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup

      - name: Execute commitlint
        run: npx commitlint --from="origin/$BASE_REF"
    env:
      BASE_REF: ${{ github.base_ref }}

  check-file-format:
    name: Check files changes follow guidelines
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup

      - name: Check if Prettier was run
        run: npx pretty-quick --check

  backwards-compatibility-test:
    name: Backwards compatibility test
    needs: [pr-test]
    uses: ./.github/workflows/backwards-compatibility-test.yml
