name: PR's
on:
  pull_request:
    types: [opened, synchronize, reopened]

env:
  PR_NUMBER: ${{ github.event.pull_request.number }}

jobs:
  pr-test:
    uses: ./.github/workflows/basic-test.yml

  pr-e2e-test:
    uses: ./.github/workflows/e2e-test.yml

  check-commit-lint:
    name: Check commit message follows guidelines
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup

      - name: Execute commitlint
        run: npx commitlint --from=origin/${{ github.base_ref }}

      - name: Get PR Title
        run: "echo 'PR Title: ${{ github.event.pull_request.title }}'"

      - name: Get PR Body
        run: 'echo "PR Body: ${{ github.event.pull_request.body }}"'

      - name: Fetch commits
        run: git fetch origin ${{ github.event.pull_request.head.ref }}

      - name: Get commit messages
        run: |
          git log --pretty=format:'%s' --abbrev-commit ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }} > commits.txt
          echo "Commit Messages:"
          cat commits.txt

  check-file-format:
    name: Check files changes follow guidelines
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup

      - name: Check if Prettier was run
        run: npx pretty-quick --check

  backwards-compatibility-test:
    needs: [pr-test]
    uses: ./.github/workflows/backwards-compatibility-test.yml

  pr-analysis:
    name: SonarCloud Pr Analysis
    runs-on: ubuntu-latest
    needs: pr-test
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis

      # Download reports
      - uses: ./.github/actions/download-coverage-report
      - uses: ./.github/actions/download-lint-report

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONARQUBE_SCANNER }}
        with:
          args: >
            -Dsonar.pullrequest.key=${{ github.env.PR_NUMBER }}
