name: Test nx@next
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # daily at 00:00

jobs:
  lint-next:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - uses: ./.github/actions/migrate
        with:
          nx-version: 'next'
      - name: Lint
        run: npx nx lint ngx-deploy-npm --fix

  build-next:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - uses: ./.github/actions/migrate
        with:
          nx-version: 'next'
      - name: Build
        run: npx nx build ngx-deploy-npm

  test-next:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - uses: ./.github/actions/migrate
        with:
          nx-version: 'next'
      - name: Test
        run: npx nx test ngx-deploy-npm

  e2e-next:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - uses: ./.github/actions/migrate
        with:
          nx-version: 'next'
      - name: E2E Test
        run: npx nx e2e ngx-deploy-npm-e2e
